version: '3.8'

services:
  blazorservertiered-blazor:
    image: demoabpapp/blazorservertiered-blazor:latest
    container_name: blazorservertiered-blazor
    build:
      context: ../../
      dockerfile: src/demoabpapp.blazorservertiered.Blazor/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=f0442807-3ebc-4e31-a839-e3a32a483f17
      - App__SelfUrl=https://localhost:44314
      - AuthServer__RequireHttpsMetadata=false      
      - AuthServer__Authority=https://localhost:44334/
      - AuthServer__IsContainerizedOnLocalhost=true
      - AuthServer__MetaAddress=http://blazorservertiered-authserver
      - RemoteServices__AbpAccountPublic__BaseUrl=http://blazorservertiered-authserver 
      - RemoteServices__Default__BaseUrl=http://blazorservertiered-api
      - Redis__Configuration=redis
    ports:
      - "44314:443"
    depends_on:    
      - blazorservertiered-api
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  blazorservertiered-api:
    image: demoabpapp/blazorservertiered-api:latest
    container_name: blazorservertiered-api
    hostname: blazorservertiered-api
    build:
      context: ../../
      dockerfile: src/demoabpapp.blazorservertiered.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=f0442807-3ebc-4e31-a839-e3a32a483f17
      - App__SelfUrl=https://localhost:44354
      - App__HealthCheckUrl=http://blazorservertiered-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://blazorservertiered-authserver
      - AuthServer__MetaAddress=https://localhost:44334
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=blazorservertiered;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  blazorservertiered-authserver:
    image: demoabpapp/blazorservertiered-authserver:latest
    container_name: blazorservertiered-authserver
    build:
      context: ../../
      dockerfile: src/demoabpapp.blazorservertiered.AuthServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - App__SelfUrl=https://localhost:44334
      - App__CorsOrigins=https://localhost:44314,https://localhost:44354
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44334
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=f0442807-3ebc-4e31-a839-e3a32a483f17
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=blazorservertiered;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44334:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  db-migrator:
    image: demoabpapp/blazorservertiered-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/blazorservertiered.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__blazorservertiered_BlazorServerTiered__RootUrl=https://localhost:44314
      - OpenIddict__Applications__blazorservertiered_Swagger__RootUrl=https://localhost:44354
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=blazorservertiered;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      
volumes:
  sqldata:
    name: blazorservertiered_sqldata
networks:
  abp-network:
    name: blazorservertiered-network
    driver: bridge
